export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "https://api.manus.im",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  tiktokAppKey: process.env.TIKTOK_APP_KEY ?? "",
  tiktokAppSecret: process.env.TIKTOK_APP_SECRET ?? "",
  tiktokAppId: process.env.TIKTOK_APP_ID ?? "",
  tiktokRedirectUrl: process.env.TIKTOK_REDIRECT_URL ?? "",
  githubClientId: process.env.GITHUB_CLIENT_ID ?? "Ov23li2gjbSYAvEN6Iua",
  githubClientSecret: process.env.GITHUB_CLIENT_SECRET ?? "4909b6c2671af0b4299e0c6d994ec586cb0c44f0",
  googleClientId: process.env.GOOGLE_CLIENT_ID ?? "38627040583-ug6omdfnro8mdbqagen7dab53vrh6b59.apps.googleusercontent.com",
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET ?? "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",
};
